services:
  api-gateway:
    build:
      context: ../../services/api-gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENV=dev
      - INTERNAL_API_KEY=${INTERNAL_API_KEY}
      - LANGGRAPH_AGENT_URL=${LANGGRAPH_AGENT_URL}
    depends_on:
      - langgraph-agent
    restart: on-failure

  langgraph-agent:
    build:
      context: ../../services/langgraph-agent
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - ENV=dev
      - GROQ_API_KEY=${GROQ_API_KEY}
      - INTERNAL_API_KEY=${INTERNAL_API_KEY}
      - MCP_TOOL_CONFIG=${MCP_TOOL_CONFIG}
    depends_on:
      - weather-server
    restart: on-failure

  weather-server:
    build:
      context: ../../services/mcp-servers/weather-server
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - ENV=dev
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - INTERNAL_API_KEY=${INTERNAL_API_KEY}
    restart: on-failure

  web-app:
    build:
      context: ../../services/ui
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - ENV=dev
      - API_GATEWAY_URL=${API_GATEWAY_URL}
      - INTERNAL_API_KEY=${INTERNAL_API_KEY}
      - BACKEND_URL=${BACKEND_URL}
    restart: on-failure

networks:
  default:
    driver: bridge
